// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCT32PEFnec9MC9b6gglnu4SrrXm1CQAms',
    appId: '1:292861273477:web:d108f78ba9a86b8e3fd0ec',
    messagingSenderId: '292861273477',
    projectId: 'bookfahasaflutter',
    authDomain: 'bookfahasaflutter.firebaseapp.com',
    storageBucket: 'bookfahasaflutter.firebasestorage.app',
    measurementId: 'G-4QLXVQVPMB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCMCRJXcJ91aVGrGLJpQuf6ZKZIqBlf0Q',
    appId: '1:292861273477:android:d383399dc2be947c3fd0ec',
    messagingSenderId: '292861273477',
    projectId: 'bookfahasaflutter',
    storageBucket: 'bookfahasaflutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCS8C2VJCHrOHonGYZx60E8kkAJx-RGC_Y',
    appId: '1:292861273477:ios:dc8b2aada200c5d93fd0ec',
    messagingSenderId: '292861273477',
    projectId: 'bookfahasaflutter',
    storageBucket: 'bookfahasaflutter.firebasestorage.app',
    iosBundleId: 'com.example.doanflutterfahasa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCS8C2VJCHrOHonGYZx60E8kkAJx-RGC_Y',
    appId: '1:292861273477:ios:dc8b2aada200c5d93fd0ec',
    messagingSenderId: '292861273477',
    projectId: 'bookfahasaflutter',
    storageBucket: 'bookfahasaflutter.firebasestorage.app',
    iosBundleId: 'com.example.doanflutterfahasa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCT32PEFnec9MC9b6gglnu4SrrXm1CQAms',
    appId: '1:292861273477:web:d2bb4df025e6e1b33fd0ec',
    messagingSenderId: '292861273477',
    projectId: 'bookfahasaflutter',
    authDomain: 'bookfahasaflutter.firebaseapp.com',
    storageBucket: 'bookfahasaflutter.firebasestorage.app',
    measurementId: 'G-BTYWBPVP38',
  );
}
